from lib.tools import *

from lsst.ip.diffim.subtractImages import AlardLuptonSubtractTask, AlardLuptonSubtractConfig
from lsst.ip.diffim import detectAndMeasure
#from lsst.ip.diffim import DetectAndMeasureTask #?

from lsst.ap.association import DiaPipelineTask, DiaPipelineConfig, TransformDiaSourceCatalogTask

import pandas as pd



#======================================
# Define some empty tables stored in apdb？
# diaObj
# diaSrc (different from the one generated by diffim)

DiaObject_empty = pd.read_csv("../DiaObject_empty.csv")
DiaSource_empty = pd.read_csv("../DiaSource_empty.csv")
SSObject_empty = pd.read_csv("../SSObject_empty.csv")


#======================================
def run_AL(templateExposure, scienceExposure, sources): 

    # image subtraction
    
    config = AlardLuptonSubtractConfig()
    
    try:
        config.sourceSelector.value.unresolved.name = "base_ClassificationExtendedness_value" # 1 for extended source
    except:
        pass

    alTask = AlardLuptonSubtractTask(config=config)

    al_result = alTask.run(templateExposure, scienceExposure, sources)

    return al_result



def detect_measure(scienceExposure, templateExposure, difference): 
    
    # running detection on a difference image (al_result.difference)

    task = detectAndMeasure.DetectAndMeasureTask()
    
    diff_dm_result = task.run(scienceExposure, templateExposure, difference)

    return diff_dm_result

   

def diaSrc2pdDf(diaSourceCat, diffIm, band):

    # Convert SourceCatalog to Pandas dataframe
    initInputs = {}
    initInputs['diaSourceSchema'] = diaSourceCat
    task = TransformDiaSourceCatalogTask(initInputs)
    res = task.run(diaSourceCat, diffIm, band)
    
    return res.diaSourceTable
    
    

def get_object(diaSourceCat, diffIm, band, preloadedDiaSources=None, diaObjects=pd.DataFrame(), solarSystemObjectTable=None):
    
    # https://pipelines.lsst.io/py-api/lsst.ap.association.DiaPipelineTask.html#lsst.ap.association.DiaPipelineTask.associateDiaSources
    # https://github.com/lsst/ap_association/blob/7cc9b91cc9da2cce2b05af381bd34bbc5b5e6069/python/lsst/ap/association/diaPipe.py#

    diaSourceTable = diaSrc2pdDf(diaSourceCat, diffIm, band)
    
    config = DiaPipelineConfig()
    config.apdb_config_url = "apdb_config.py"
    
    task = DiaPipelineTask(config=config)

#    if diaObjects is None:
#        print("diaObjects is None!")
#        struct = task.createNewDiaObjects(diaSourceTable)
#        print("diaSources: ", struct.diaSources)
#        print("newDiaObjects: ", struct.newDiaObjects)
#        print("nNewDiaObjects: ", struct.nNewDiaObjects)

        #return struct.newDiaObjects
        
#    else:
    assocResults = task.associateDiaSources(diaSourceTable, solarSystemObjectTable, diffIm, diaObjects)
    print("associatedDiaSources: ", assocResults.associatedDiaSources)
    print("newDiaObjects: ", assocResults.newDiaObjects)
    print("newDiaSources: ", assocResults.newDiaSources)
    print("marginalDiaSources: ", assocResults.marginalDiaSources)
        #return struct.newDiaObjects

    #------------------------
    print("\nMerging...")
    
    if preloadedDiaSources is None:
        preloadedDiaSources_new = pd.DataFrame(columns=['diaObjectId', 'diaSourceId'])
        preloadedDiaSources_new.set_index("diaObjectId", inplace=True)
        print(preloadedDiaSources_new)
        
    mergedDiaSourceHistory, mergedDiaObjects, updatedDiaObjectIds = task.mergeAssociatedCatalogs(
            preloadedDiaSources_new,
            assocResults.associatedDiaSources,
            diaObjects,
            assocResults.newDiaObjects,
            diffIm
        )

    print("mergedDiaObjects: ", mergedDiaObjects)
    
    return mergedDiaObjects
    